### ISSUE TITLE
Page blanche après connection SSO CAS

### ISSUE THREAD

**Issue by nothing-fr** [JeromeDevome/GRR#245]
**PAGE BLANCHE APRES LA CONNECTION D'UN UTILISATEUR VIA SSO CAS**
Une fois connecté, l'utilisateur arrive sur une page blanche et ne peut rien faire.
En tant qu'administrateurs, nous accédons bien a l'application et au backend d'admin.

**Infos GRR**
Version de GRR : 4.0.1
Version PHP : 8.1.2
Problème suite à une installation ou mise à jour : 
Après migration vers Ubuntu 22.04 avec PHP8.1 et GRR 4.0.1 depuis une Ubuntu 18.04 avec PHP7.2 et GRR 3.4

**Reproduire**
Étapes pour reproduire le comportement :
1. Connection via SSO CAS par un utilisateur

**Comportement attendu**
L'utilisateur à accès a l'application et peut faire des réservations

**Captures d'écran**
-N/A

**Ordinateur (veuillez compléter les informations suivantes) :**
  - OS : Windows
  - Navigateur : Firefox / Edge

**Contexte supplémentaire**
J'ai des erreurs PHP dans les logs : 
```
[Mon Feb 27 10:37:59.372572 2023] [proxy_fcgi:error] [pid 16010] [client XX.XX.XX.XX:56022] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught TypeError: substr(): Argument #3 ($length) must be of type ?int, string given in /var/www/grr/include/functions.inc.php:1986\nStack trace:\n#0 /var/www/grr/include/functions.inc.php(1986): substr()\n#1 /var/www/grr/include/session.inc.php(582): compare_ip_adr()\n#2 /var/www/grr/index.php(127): grr_opensession()\n#3 {main}\n  thrown in /var/www/grr/include/functions.inc.php on line 1986', referer: https://cas.XXXXX.XXX/

[Mon Feb 27 10:39:49.840727 2023] [proxy_fcgi:error] [pid 16329] [client XX.XX.XX.XX:45708] AH01071: Got error 'PHP message: PHP Warning:  session_name(): Session name cannot be changed when a session is active in /var/www/grr/include/session.inc.php on line 608PHP message: PHP Warning:  Undefined array key "changepwd" in /var/www/grr/include/session.inc.php on line 667PHP message: PHP Warning:  Undefined array key "changepwd" in /var/www/grr/include/session.inc.php on line 745', referer: https://grr.XXXX.XXXX/
```

**Comment by nothing-fr** [comment]
Réponse a moi meme : 
Le problème était la restriction IP, je ne sais pas pourquoi mais suite a la migration elle avait pour valeur l'url de déco du CAS...

Par contre je n'ai pas réussi a la remettre a zéro via l'interface d’administration et j'ai du faire un update en base pour résoudre le soucis.
